version: '3'

services:
  db-server:
    container_name: db-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"
    networks:
      - jwt-store-network
    volumes:
      - jwt-store-data:/var/opt/mssql

networks:
  jwt-store-network:
    name: jwt-store-network

volumes:
  jwt-store-data:
