<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\JwtStore.Core\JwtStore.Core.csproj" />
    <ProjectReference Include="..\JwtStore.UseCases\JwtStore.UseCases.csproj" />
  </ItemGroup>

</Project>
